name: Devathon Project
description: A project for the Devathon contest
version: 1.0.0
author: XXLCreeper

main: org.devathon.contest2016.DevathonPlugin

commands:
  turtle:
    description: mining turtle


